# Generated by Django 4.2.2 on 2023-07-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0005_alter_feedbackcomment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackcomment",
            name="section",
            field=models.TextField(null=True, verbose_name="구간"),
        ),
        migrations.AlterField(
            model_name="feedbackcomment",
            name="title",
            field=models.TextField(null=True, verbose_name="제목"),
        ),
    ]
