# Generated by Django 4.2.2 on 2023-08-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0006_alter_feedbackcomment_section_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "피드백 파일", "verbose_name_plural": "피드백 파일"},
        ),
        migrations.AlterField(
            model_name="feedbackmessage",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="feedbacks.feedback",
                verbose_name="피드백 파일",
            ),
        ),
    ]
