# Railpack configuration for Django project in subdirectory
providers = ["python"]

[provider.python]
version = "3.11"

[build]
# Install dependencies from root requirements.txt first
cmd = """
pip install --no-cache-dir --upgrade pip && \
pip install --no-cache-dir -r requirements.txt && \
pip install --no-cache-dir gunicorn uvicorn[standard] && \
cd vridge_back && \
export PYTHONPATH=/app/vridge_back && \
python manage.py collectstatic --noinput --clear || echo "Static collection skipped"
"""

[start]
# Start Gunicorn ASGI server with uvicorn worker
cmd = "cd vridge_back && python manage.py migrate --noinput && gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:${PORT:-8000} --chdir /app/vridge_back"

[variables]
DJANGO_SETTINGS_MODULE = "config.settings"
PYTHONPATH = "/app/vridge_back"
PYTHONUNBUFFERED = "1"