# Railpack Configuration for VideoPlanet Django Backend

[build]
# Build in the Django backend directory
cmd = """
cd vridge_back && \
pip install --upgrade pip && \
pip install -r requirements.txt && \
python manage.py collectstatic --noinput --clear || echo 'Static collection skipped'
"""

[start]
# Start the Django application with Daphne (ASGI server)
cmd = "cd vridge_back && daphne -b 0.0.0.0 -p $PORT config.asgi:application"

[variables]
# Django environment variables
DJANGO_SETTINGS_MODULE = "config.settings"
PYTHONPATH = "/app/vridge_back"
PYTHONUNBUFFERED = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

# Python version specification for Railpack
[providers.python]
version = "3.11"