version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: videoplanet_postgres
    environment:
      POSTGRES_DB: videoplanet_db
      POSTGRES_USER: videoplanet_user
      POSTGRES_PASSWORD: videoplanet_pass_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ko_KR.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U videoplanet_user -d videoplanet_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - videoplanet_network

  redis:
    image: redis:7-alpine
    container_name: videoplanet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - videoplanet_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: videoplanet_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@videoplanet.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass_2024
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - videoplanet_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  videoplanet_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16