# Nixpacks configuration for VideoPlanet Django Backend
[build]
buildCommand = """
cd vridge_back && 
pip install --upgrade pip && 
pip install -r requirements.txt && 
python manage.py collectstatic --noinput --clear
"""

[start]
cmd = "cd vridge_back && daphne -b 0.0.0.0 -p $PORT config.asgi:application"

[variables]
# Django settings
DJANGO_SETTINGS_MODULE = "config.settings"
DEBUG = "False"
PYTHONPATH = "/app/vridge_back"

# Database settings for Railway
DATABASE_URL = { default = "postgresql://user:pass@localhost:5432/dbname" }
REDIS_URL = { default = "redis://localhost:6379" }

# Build variables
PYTHONUNBUFFERED = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[phases.build]
cmds = [
    "echo 'Building VideoPlanet Django Backend...'",
    "cd vridge_back",
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput --clear || echo 'Static files collection skipped'"
]

[phases.start]
cmd = "cd vridge_back && daphne -b 0.0.0.0 -p ${PORT:-8000} config.asgi:application"