[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "pip install gunicorn uvicorn[standard]"
]

[start]
cmd = "cd vridge_back && python manage.py migrate --noinput && gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:${PORT:-8000} --chdir /app/vridge_back"

[variables]
DJANGO_SETTINGS_MODULE = "config.settings"
PYTHONPATH = "/app/vridge_back"