[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmd = "pip install --upgrade pip && pip install -r vridge_back/requirements.txt"

[phases.build]
cmd = "cd vridge_back && python manage.py collectstatic --noinput --clear"

[start]
cmd = "cd vridge_back && python -m daphne -b 0.0.0.0 -p $PORT config.asgi:application"

[variables]
DJANGO_SETTINGS_MODULE = "config.settings"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PYTHON_VERSION = "3.11"