[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]  
cmd = "cd vridge_back && pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt"

[phases.build]
cmd = "cd vridge_back && python manage.py collectstatic --noinput --clear"

[start]
cmd = "cd vridge_back && daphne -b 0.0.0.0 -p $PORT config.asgi:application"

[variables]
DJANGO_SETTINGS_MODULE = "config.settings"
PYTHONPATH = "/app/vridge_back"
PYTHONUNBUFFERED = "1"