# Generated by Django 4.2.2 on 2023-07-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0009_alter_project_basic_plan_alter_project_confirmation_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="members",
            options={"verbose_name": "멤버", "verbose_name_plural": "멤버"},
        ),
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("memo", models.TextField(null=True, verbose_name="메모")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memos",
                        to="projects.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트 메모",
                "verbose_name_plural": "프로젝트 메모",
            },
        ),
    ]
