# Generated by Django 4.2.2 on 2023-07-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_alter_members_options_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="date",
            field=models.DateField(null=True, verbose_name="날짜"),
        ),
    ]
