# Generated by Django 4.2.2 on 2023-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_memo_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "files",
                    models.FileField(upload_to="sample_file", verbose_name="샘플파일"),
                ),
            ],
            options={
                "verbose_name": "샘플파일",
                "verbose_name_plural": "샘플파일",
            },
        ),
    ]
