# Generated by Django 4.2.2 on 2023-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_samplefiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicplan",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="끝나는 날짜"),
        ),
        migrations.AlterField(
            model_name="basicplan",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 날짜"),
        ),
        migrations.AlterField(
            model_name="confirmation",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="끝나는 날짜"),
        ),
        migrations.AlterField(
            model_name="confirmation",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 날짜"),
        ),
        migrations.AlterField(
            model_name="filming",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="끝나는 날짜"),
        ),
        migrations.AlterField(
            model_name="filming",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 날짜"),
        ),
        migrations.AlterField(
            model_name="postwork",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="끝나는 날짜"),
        ),
        migrations.AlterField(
            model_name="postwork",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 날짜"),
        ),
        migrations.AlterField(
            model_name="storyboard",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="끝나는 날짜"),
        ),
        migrations.AlterField(
            model_name="storyboard",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 날짜"),
        ),
        migrations.AlterField(
            model_name="videodelivery",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="끝나는 날짜"),
        ),
        migrations.AlterField(
            model_name="videodelivery",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 날짜"),
        ),
        migrations.AlterField(
            model_name="videoedit",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="끝나는 날짜"),
        ),
        migrations.AlterField(
            model_name="videoedit",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 날짜"),
        ),
        migrations.AlterField(
            model_name="videopreview",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="끝나는 날짜"),
        ),
        migrations.AlterField(
            model_name="videopreview",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 날짜"),
        ),
    ]
