release: python manage.py migrate && python manage.py collectstatic --noinput
web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 4 --worker-class sync --max-requests 1000 --max-requests-jitter 50 --timeout 120
worker: python manage.py runworker
daphne: daphne -b 0.0.0.0 -p $PORT config.asgi:application