# Generated by Django 4.2.2 on 2023-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_email_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                    ("kakao", "Kakao"),
                    ("naver", "Naver"),
                ],
                default="email",
                max_length=50,
                verbose_name="로그인 방식",
            ),
        ),
    ]
