# Generated by Django 4.2.2 on 2023-10-26 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_login_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(null=True, verbose_name="날짜")),
                ("memo", models.TextField(null=True, verbose_name="메모")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="메모",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 메모",
                "verbose_name_plural": "사용자 메모",
            },
        ),
    ]
