# Generated by Django 4.2.2 on 2023-07-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnlineVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("link", models.TextField(null=True, verbose_name="링크")),
            ],
            options={
                "verbose_name": "온라인 강의",
                "verbose_name_plural": "온라인 강의",
                "ordering": ("-created",),
            },
        ),
    ]
